<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseDataEntryBPO" Class="DataEntryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.10.10.248\BPOSERVER;Initial Catalog=DatabaseDataEntryBPO;Persist Security Info=True;User ID=sa" SettingsObjectName="PhieuKiemKe.Properties.Settings" SettingsPropertyName="DatabaseDataEntryBPOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Version" Member="tbl_Versions">
    <Type Name="tbl_Version">
      <Column Name="IDProject" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="IDVersion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_int_auto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoTaChucNangMoi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_TokenLogin" Member="tbl_TokenLogins">
    <Type Name="tbl_TokenLogin">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IDProject" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DateLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_User" Member="tbl_Users">
    <Type Name="tbl_User">
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IDRole" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IDNhanVien" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Group_Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NotGoodUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.UpdateTimeFree" Method="UpdateTimeFree">
    <Parameter Name="Token" Parameter="token" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="freetime" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.updateToken" Method="updateToken">
    <Parameter Name="username" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="idproject" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="token" Type="System.String" DbType="NVarChar(255)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertLoginTime_new" Method="InsertLoginTime_new">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TimeLogin" Parameter="timeLogin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="WindowUser" Parameter="windowUser" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="MachineName" Parameter="machineName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Token" Parameter="token" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="project" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KiemTraLogin" Method="KiemTraLogin">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetListUser" Method="GetListUser">
    <ElementType Name="GetListUserResult">
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IDRole" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Group_Level" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NotGoodUser" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetListRole" Method="GetListRole">
    <ElementType Name="GetListRoleResult">
      <Column Name="RoleID" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateUsername" Method="UpdateUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IDRole" Parameter="iDRole" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IDNhanVien" Parameter="iDNhanVien" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GroupLevel" Parameter="groupLevel" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertUsername" Method="InsertUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="IDRole" Parameter="iDRole" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NhanVien" Parameter="nhanVien" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="GroupLevel" Parameter="groupLevel" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUsername" Method="DeleteUsername">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
</Database>